INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '숨겨진 호숫가', 209) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '아르마의 은신처', 209) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '숨겨진 동굴', 209) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '세 갈래길 1', 208) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '동굴의 서쪽길 1', 208) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '동굴의 서쪽길 2', 208) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '동굴의 동쪽길 1', 208) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '동굴의 동쪽길 2', 208) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '세 갈래길 2', 208) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '동굴 위쪽', 208) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '동굴 아래쪽', 208) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '동굴의 깊숙한 곳', 208) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '화염과 영혼의 영토', 206) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '화염의 영토', 205) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '암석과 화염의 영토', 205) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '암석의 영토', 204) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '풍화된 슬픔과 즐거움의 땅', 203) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '풍화된 즐거움의 땅', 203) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '풍화된 분노와 슬픔의 땅', 202) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '풍화된 슬픔의 땅', 202) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '풍화된 기쁨과 분노의 땅', 201) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '풍화된 분노의 땅', 201) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('소멸의 여로', '풍화된 기쁨의 땅', 200) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', '숨겨진 M타워', 213) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', '숨겨진 지하열차', 212) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', '숨겨진 연구열차', 210) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', 'M타워 2', 209) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', 'M타워 3', 209) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', 'M타워 4', 209) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', '지하열차 2', 208) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', '지하열차 3', 208) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', '지하열차 1', 207) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', '지상열차 2', 208) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', '지상열차 3', 208) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', '지상열차 1', 207) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', 'T-boy의 연구열차 2', 206) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', 'T-boy의 연구열차 1', 206) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', 'T-boy의 연구열차 3', 206) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', '지하선로 5', 205) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', '지하선로 2', 205) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', '지하선로 1', 205) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', '지하선로 3', 205) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', '지하선로 4', 205) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리버스 시티', '지하선로 6', 205) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('츄츄 아일랜드', '거대한 꼬리', 219) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('츄츄 아일랜드', '고래산 정상', 219) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('츄츄 아일랜드', '고래산 중턱 1', 219) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('츄츄 아일랜드', '고래산 중턱 2', 218) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('츄츄 아일랜드', '고래산 초입', 217) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('츄츄 아일랜드', '폭포 아래', 216) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('츄츄 아일랜드', '격류지대 1', 216) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('츄츄 아일랜드', '격류지대 3', 216) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('츄츄 아일랜드', '격류지대 2', 215) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('츄츄 아일랜드', '츄츄빌리지 입구', 214) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('츄츄 아일랜드', '츄릅포레스트 깊은 곳', 213) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('츄츄 아일랜드', '몽땅 동글숲 2', 213) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('츄츄 아일랜드', '길쭉 동글숲 2', 213) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('츄츄 아일랜드', '길쭉 동글숲 1', 212) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('츄츄 아일랜드', '몽땅 동글숲 1', 212) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('츄츄 아일랜드', '알록달록 숲지대 3', 211) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('츄츄 아일랜드', '오색동산 깊은 곳', 211) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('츄츄 아일랜드', '알록달록 숲지대 2', 210) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('츄츄 아일랜드', '알록달록 숲지대 1', 211) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('츄츄 아일랜드', '동산 입구', 210) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '숨겨진 머쉬버드 숲', 220) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '숨겨진 일리야드 들판', 220) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '숨겨진 펑고스 숲', 220) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '펑고스 숲 2', 219) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '펑고스 숲 5', 219) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '펑고스 숲 1', 219) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '펑고스 숲 3', 219) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '펑고스 숲 4', 219) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '펑고스 숲 6', 219) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '일리야드 들판 3', 218) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '일리야드 들판 6', 218) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '일리야드 들판 2', 218) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '일리야드 들판 5', 218) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '일리야드 들판 1', 217) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '일리야드 들판 4', 217) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '머쉬버드 숲 3', 216) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '머쉬버드 숲 6', 216) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '머쉬버드 숲 2', 216) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '머쉬버드 숲 5', 216) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '머쉬버드 숲 1', 215) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('얌얌 아일랜드', '머쉬버드 숲 4', 215) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('꿈의 도시 레헬른', '악몽의 시계탑 1층', 226) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('꿈의 도시 레헬른', '악몽의 시계탑 2층', 226) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('꿈의 도시 레헬른', '악몽의 시계탑 5층', 228) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('꿈의 도시 레헬른', '악몽의 시계탑 3층', 227) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('꿈의 도시 레헬른', '악몽의 시계탑 4층', 228) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('꿈의 도시 레헬른', '춤추는 구두 점령지 2', 225) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('꿈의 도시 레헬른', '춤추는 구두 점령지 1', 224) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('꿈의 도시 레헬른', '본색을 드러내는 곳 2', 224) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('꿈의 도시 레헬른', '본색을 드러내는 곳 3', 224) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('꿈의 도시 레헬른', '본색을 드러내는 곳 1', 223) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('꿈의 도시 레헬른', '우승 접시의 거리 2', 223) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('꿈의 도시 레헬른', '우승 접시의 거리 1', 222) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('꿈의 도시 레헬른', '닭이 뛰노는 곳 2', 222) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('꿈의 도시 레헬른', '닭이 뛰노는 곳 3', 222) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('꿈의 도시 레헬른', '닭이 뛰노는 곳 1', 221) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('꿈의 도시 레헬른', '무법자들의 거리 3', 221) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('꿈의 도시 레헬른', '무법자들의 거리 2', 221) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('꿈의 도시 레헬른', '무법자들의 거리 1', 220) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '다섯 갈래 동굴 윗길', 240) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '다섯 갈래 동굴 사잇길', 240) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '다섯 갈래 동굴 아랫길', 240) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '정령의 나무 밑 동굴', 240) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '동굴 아랫길 깊디 깊은 곳', 239) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '동굴 아랫길 깊은 곳 2', 239) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '동굴 아랫길 깊은 곳 1', 239) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '동굴 아랫길', 237) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '동굴 윗길 깊디 깊은 곳', 239) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '동굴 윗길 깊은 곳 2', 238) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '동굴 윗길 깊은 곳 1', 238) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '동굴 윗길', 237) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '맹독과 폭발의 숲 2', 236) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '맹독과 폭발의 숲 1', 236) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '폭발의 숲', 236) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '맹독의 숲', 235) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '서리와 번개의 숲 2', 234) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '서리와 번개의 숲 1', 234) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '번개구름의 숲', 234) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '서리구름의 숲', 233) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '햇살과 흙의 숲', 232) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '흙의 숲', 232) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '물과 햇살의 숲', 231) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '햇살의 숲', 231) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('신비의 숲 아르카나', '물의 숲', 230) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기억의 늪 모라스', '그날의 트뤼에페 4', 245) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기억의 늪 모라스', '그날의 트뤼에페 3', 244) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기억의 늪 모라스', '그날의 트뤼에페 2', 243) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기억의 늪 모라스', '폐쇄구역 3', 241) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기억의 늪 모라스', '폐쇄구역 2', 241) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기억의 늪 모라스', '폐쇄구역', 241) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기억의 늪 모라스', '그림자가 춤추는 곳 4', 240) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기억의 늪 모라스', '그림자가 춤추는 곳 3', 240) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기억의 늪 모라스', '그림자가 춤추는 곳 2', 239) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기억의 늪 모라스', '형님들 구역 3', 238) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기억의 늪 모라스', '형님들 구역 2', 238) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기억의 늪 모라스', '형님들 구역', 238) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기억의 늪 모라스', '도둑고양이 출몰지 2', 237) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기억의 늪 모라스', '도둑고양이 출몰지', 237) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기억의 늪 모라스', '산호 숲으로 가는 길 4', 236) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기억의 늪 모라스', '산호 숲으로 가는 길 3', 236) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기억의 늪 모라스', '산호 숲으로 가는 길 2', 236) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('태초의 바다 에스페라', '거울에 비친 빛의 신전 4', 249) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('태초의 바다 에스페라', '거울에 비친 빛의 신전 3', 249) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('태초의 바다 에스페라', '거울에 비친 빛의 신전 2', 248) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('태초의 바다 에스페라', '거울빛에 물든 바다 7', 247) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('태초의 바다 에스페라', '거울빛에 물든 바다 6', 247) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('태초의 바다 에스페라', '거울빛에 물든 바다 5', 246) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('태초의 바다 에스페라', '거울빛에 물든 바다 4', 245) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('태초의 바다 에스페라', '거울빛에 물든 바다 3', 245) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('태초의 바다 에스페라', '거울빛에 물든 바다 2', 244) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('태초의 바다 에스페라', '생명이 시작되는 곳 7', 243) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('태초의 바다 에스페라', '생명이 시작되는 곳 6', 243) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('태초의 바다 에스페라', '생명이 시작되는 곳 5', 242) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('태초의 바다 에스페라', '생명이 시작되는 곳 4', 241) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('태초의 바다 에스페라', '생명이 시작되는 곳 3', 241) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('태초의 바다 에스페라', '생명이 시작되는 곳 2', 240) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '별이 삼켜진 심해 6', 251) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '별이 삼켜진 심해 5', 251) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '별이 삼켜진 심해 4', 251) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '별이 삼켜진 심해 3', 250) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '별이 삼켜진 심해 2', 250) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '별이 삼켜진 심해 1', 250) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '끝없이 추락하는 심해 6', 249) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '끝없이 추락하는 심해 5', 249) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '끝없이 추락하는 심해 4', 249) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '끝없이 추락하는 심해 3', 248) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '끝없이 추락하는 심해 2', 248) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '끝없이 추락하는 심해 1', 248) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '빛이 마지막으로 닿는 곳 9', 247) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '빛이 마지막으로 닿는 곳 8', 247) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '빛이 마지막으로 닿는 곳 7', 247) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '빛이 마지막으로 닿는 곳 6', 246) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '빛이 마지막으로 닿는 곳 5', 246) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '빛이 마지막으로 닿는 곳 4', 246) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '빛이 마지막으로 닿는 곳 3', 245) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '빛이 마지막으로 닿는 곳 2', 245) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('셀라스', '빛이 마지막으로 닿는 곳 1', 245) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('문브릿지', '공허의 파도 6', 254) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('문브릿지', '공허의 파도 5', 254) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('문브릿지', '공허의 파도 4', 254) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('문브릿지', '공허의 파도 3', 254) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('문브릿지', '공허의 파도 2', 254) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('문브릿지', '공허의 파도 1', 254) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('문브릿지', '미지의 안개 6', 253) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('문브릿지', '미지의 안개 5', 253) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('문브릿지', '미지의 안개 4', 252) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('문브릿지', '미지의 안개 3', 253) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('문브릿지', '미지의 안개 2', 253) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('문브릿지', '미지의 안개 1', 252) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('문브릿지', '사상의 경계 6', 251) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('문브릿지', '사상의 경계 5', 251) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('문브릿지', '사상의 경계 4', 250) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('문브릿지', '사상의 경계 3', 251) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('문브릿지', '사상의 경계 2', 251) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('문브릿지', '사상의 경계 1', 250) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('고통의 미궁', '고통의 미궁 최심부 6', 259) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('고통의 미궁', '고통의 미궁 최심부 5', 259) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('고통의 미궁', '고통의 미궁 최심부 4', 259) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('고통의 미궁', '고통의 미궁 최심부 3', 259) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('고통의 미궁', '고통의 미궁 최심부 2', 259) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('고통의 미궁', '고통의 미궁 최심부 1', 259) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('고통의 미궁', '고통의 미궁 중심부 7', 258) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('고통의 미궁', '고통의 미궁 중심부 6', 258) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('고통의 미궁', '고통의 미궁 중심부 5', 258) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('고통의 미궁', '고통의 미궁 중심부 4', 258) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('고통의 미궁', '고통의 미궁 중심부 3', 257) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('고통의 미궁', '고통의 미궁 중심부 2', 257) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('고통의 미궁', '고통의 미궁 중심부 1', 257) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('고통의 미궁', '고통의 미궁 내부 6', 256) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('고통의 미궁', '고통의 미궁 내부 5', 256) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('고통의 미궁', '고통의 미궁 내부 4', 256) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('고통의 미궁', '고통의 미궁 내부 3', 255) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('고통의 미궁', '고통의 미궁 내부 2', 255) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('고통의 미궁', '고통의 미궁 내부 1', 255) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리멘', '세계가 끝나는 곳 2-8', 264) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리멘', '세계가 끝나는 곳 2-7', 264) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리멘', '세계가 끝나는 곳 2-6', 264) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리멘', '세계가 끝나는 곳 2-5', 264) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리멘', '세계가 끝나는 곳 2-4', 264) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리멘', '세계가 끝나는 곳 2-3', 263) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리멘', '세계가 끝나는 곳 1-9', 263) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리멘', '세계가 끝나는 곳 1-8', 263) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리멘', '세계가 끝나는 곳 1-7', 263) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리멘', '세계가 끝나는 곳 1-6', 263) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리멘', '세계가 끝나는 곳 1-5', 263) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리멘', '세계가 끝나는 곳 1-4', 262) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리멘', '세계의 눈물 중단 4', 262) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리멘', '세계의 눈물 중단 3', 262) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리멘', '세계의 눈물 중단 2', 262) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리멘', '세계의 눈물 중단 1', 261) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리멘', '세계의 눈물 하단 3', 261) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리멘', '세계의 눈물 하단 2', 261) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('리멘', '세계의 눈물 하단 1', 260) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '불타는 왕립 도서관 제 6 구역', 264) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '불타는 왕립 도서관 제 5 구역', 264) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '불타는 왕립 도서관 제 4 구역', 264) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '불타는 왕립 도서관 제 3 구역', 264) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '불타는 왕립 도서관 제 2 구역', 264) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '불타는 왕립 도서관 제 1 구역', 264) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '격전의 동쪽 성벽 6', 263) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '격전의 동쪽 성벽 5', 263) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '격전의 동쪽 성벽 4', 263) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '격전의 동쪽 성벽 3', 263) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '격전의 동쪽 성벽 2', 263) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '격전의 동쪽 성벽 1', 263) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '격전의 서쪽 성벽 4', 262) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '격전의 서쪽 성벽 3', 262) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '격전의 서쪽 성벽 2', 262) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '격전의 서쪽 성벽 1', 262) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '왕립 도서관 제 6 구역', 261) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '왕립 도서관 제 5 구역', 261) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '왕립 도서관 제 4 구역', 261) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '왕립 도서관 제 3 구역', 261) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '왕립 도서관 제 2 구역', 261) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '왕립 도서관 제 1 구역', 261) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '세르니움 동쪽 성벽 3', 261) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '세르니움 동쪽 성벽 2', 261) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '세르니움 동쪽 성벽 1', 261) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '세르니움 서쪽 성벽 3', 260) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '세르니움 서쪽 성벽 2', 260) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '세르니움 서쪽 성벽 1', 260) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '해변 암석 지대 4', 260) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '해변 암석 지대 3', 260) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '해변 암석 지대 2', 260) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('세르니움', '해변 암석 지대 1', 260) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('호텔 아르크스', '종착지 없는 횡단열차 6', 269) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('호텔 아르크스', '종착지 없는 횡단열차 5', 269) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('호텔 아르크스', '종착지 없는 횡단열차 4', 269) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('호텔 아르크스', '종착지 없는 횡단열차 3', 268) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('호텔 아르크스', '종착지 없는 횡단열차 2', 268) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('호텔 아르크스', '종착지 없는 횡단열차 1', 268) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('호텔 아르크스', '낭만이 저무는 자동차 극장 6', 267) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('호텔 아르크스', '낭만이 저무는 자동차 극장 5', 267) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('호텔 아르크스', '낭만이 저무는 자동차 극장 4', 267) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('호텔 아르크스', '낭만이 저무는 자동차 극장 3', 266) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('호텔 아르크스', '낭만이 저무는 자동차 극장 2', 266) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('호텔 아르크스', '낭만이 저무는 자동차 극장 1', 266) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('호텔 아르크스', '무법자들이 지배하는 황야 4', 265) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('호텔 아르크스', '무법자들이 지배하는 황야 3', 265) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('호텔 아르크스', '무법자들이 지배하는 황야 2', 265) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('호텔 아르크스', '무법자들이 지배하는 황야 1', 265) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('오디움', '잠긴 문 뒤 실험실 4', 274) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('오디움', '잠긴 문 뒤 실험실 3', 274) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('오디움', '잠긴 문 뒤 실험실 2', 274) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('오디움', '잠긴 문 뒤 실험실 1', 273) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('오디움', '볕 드는 실험실 3', 272) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('오디움', '볕 드는 실험실 2', 272) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('오디움', '볕 드는 실험실 1', 272) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('오디움', '점령당한 골목 4', 271) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('오디움', '점령당한 골목 3', 271) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('오디움', '점령당한 골목 2', 271) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('오디움', '점령당한 골목 1', 271) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('오디움', '성문으로 가는 길 5', 270) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('오디움', '성문으로 가는 길 4', 270) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('오디움', '성문으로 가는 길 3', 270) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('오디움', '성문으로 가는 길 2', 270) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('오디움', '성문으로 가는 길 1', 270) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('도원경', '참혹한 흔적의 겨울 5', 279) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('도원경', '참혹한 흔적의 겨울 4', 279) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('도원경', '참혹한 흔적의 겨울 3', 279) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('도원경', '참혹한 흔적의 겨울 2', 279) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('도원경', '참혹한 흔적의 겨울 1', 278) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('도원경', '색깔이 옅은 가을 5', 277) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('도원경', '색깔이 옅은 가을 4', 277) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('도원경', '색깔이 옅은 가을 3', 277) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('도원경', '색깔이 옅은 가을 2', 277) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('도원경', '색깔이 옅은 가을 1', 277) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('도원경', '빛이 약한 여름 5', 276) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('도원경', '빛이 약한 여름 4', 276) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('도원경', '빛이 약한 여름 3', 276) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('도원경', '빛이 약한 여름 2', 276) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('도원경', '빛이 약한 여름 1', 276) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('도원경', '생기가 돌아오는 봄 5', 275) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('도원경', '생기가 돌아오는 봄 4', 275) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('도원경', '생기가 돌아오는 봄 3', 275) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('도원경', '생기가 돌아오는 봄 2', 275) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('도원경', '생기가 돌아오는 봄 1', 275) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('아르테리아', '최상층 통로 8', 284) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('아르테리아', '최상층 통로 7', 284) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('아르테리아', '최상층 통로 6', 284) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('아르테리아', '최상층 통로 5', 284) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('아르테리아', '최상층 통로 4', 284) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('아르테리아', '최상층 통로 3', 284) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('아르테리아', '최상층 통로 2', 284) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('아르테리아', '최상층 통로 1', 284) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('아르테리아', '최하층 통로 6', 283) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('아르테리아', '최하층 통로 5', 283) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('아르테리아', '최하층 통로 4', 283) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('아르테리아', '최하층 통로 3', 282) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('아르테리아', '최하층 통로 2', 282) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('아르테리아', '최하층 통로 1', 282) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('아르테리아', '외곽 전투지역 2', 281) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('아르테리아', '외곽 전투지역 1', 280) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('아르테리아', '동쪽 외곽지역', 281) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('아르테리아', '남쪽 외곽지역', 281) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('아르테리아', '서쪽 외곽지역', 280) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('아르테리아', '북쪽 외곽지역', 280) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('카르시온', '가라앉은 유적지 4', 289) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('카르시온', '가라앉은 유적지 3', 289) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('카르시온', '가라앉은 유적지 2', 289) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('카르시온', '가라앉은 유적지 1', 289) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('카르시온', '숨이 멎어드는 동굴 4', 289) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('카르시온', '숨이 멎어드는 동굴 3', 289) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('카르시온', '숨이 멎어드는 동굴 2', 289) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('카르시온', '숨이 멎어드는 동굴 1', 289) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('카르시온', '어둠이 내리는 나무줄기 3', 288) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('카르시온', '어둠이 내리는 나무줄기 2', 288) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('카르시온', '어둠이 내리는 나무줄기 1', 288) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('카르시온', '휘감기는 숲 3', 288) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('카르시온', '휘감기는 숲 2', 287) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('카르시온', '휘감기는 숲 1', 287) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('카르시온', '잔잔한 해안가 3', 286) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('카르시온', '잔잔한 해안가 2', 286) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('카르시온', '잔잔한 해안가 1', 286) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('카르시온', '거대 산호 군락 3', 286) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('카르시온', '거대 산호 군락 2', 285) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('카르시온', '거대 산호 군락 1', 285) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '환영의 길 4', 294) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '환영의 길 3', 294) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '환영의 길 2', 294) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '환영의 길 1', 294) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '밤의 길 4', 294) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '밤의 길 3', 294) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '밤의 길 2', 294) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '밤의 길 1', 294) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '영원과 운명의 전쟁터 3', 293) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '영원과 운명의 전쟁터 2', 293) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '영원과 운명의 전쟁터 1', 293) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '심판과 운명의 전쟁터 3', 292) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '심판과 운명의 전쟁터 2', 292) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '심판과 운명의 전쟁터 1', 292) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '섭리와 운명의 전쟁터 3', 291) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '섭리와 운명의 전쟁터 2', 291) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '섭리와 운명의 전쟁터 1', 291) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '재와 침묵의 땅 5', 291) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '재와 침묵의 땅 4', 291) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '재와 침묵의 땅 3', 291) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '재와 침묵의 땅 2', 290) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('탈라하트', '재와 침묵의 땅 1', 290) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '고브의 작업실 1', 299) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '고브의 작업실 2', 299) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '고브의 작업실 3', 299) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '고브의 작업실 4', 299) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '고브의 작업실 5', 299) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '고브의 작업실 6', 299) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '고브의 작업실 7', 299) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '고브의 작업실 8', 299) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '로봇 창고 5', 298) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '로봇 창고 6', 298) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '로봇 창고 7', 298) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '로봇 창고 8', 298) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '로봇 창고 1', 297) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '로봇 창고 2', 297) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '로봇 창고 3', 297) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '로봇 창고 4', 297) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '지하 3층 1구역', 296) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '지하 3층 2구역', 296) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '지하 4층', 296) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '지하 1층', 295) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '지하 2층 1구역', 295) ON CONFLICT (region_name, map_name) DO NOTHING;
INSERT INTO hunting_grounds (region_name, map_name, max_monster_level) VALUES ('기어드락', '지하 2층 2구역', 295) ON CONFLICT (region_name, map_name) DO NOTHING;
