-- Static catalog from docs/boss_drop_items.md; only weekly/monthly bosses.
ALTER TABLE boss_drop_items
    ADD COLUMN item_kind VARCHAR(16) NOT NULL DEFAULT 'RANDOM',
    ADD COLUMN default_quantity INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN is_active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE boss_drop_items
    ADD CONSTRAINT chk_boss_drop_items_kind CHECK (item_kind IN ('CRYSTAL', 'FIXED', 'RANDOM')),
    ADD CONSTRAINT chk_boss_drop_items_default_quantity CHECK (default_quantity > 0);

INSERT INTO boss_master (boss_name, difficulty, reset_period, crystal_price, boss_image, sort_order)
VALUES
    ('자쿰', 'CHAOS', 'WEEKLY', 0, NULL, 1),
    ('매그너스', 'HARD', 'WEEKLY', 0, NULL, 2),
    ('반반', 'CHAOS', 'WEEKLY', 0, NULL, 3),
    ('피에르', 'CHAOS', 'WEEKLY', 0, NULL, 4),
    ('블러디 퀸', 'CHAOS', 'WEEKLY', 0, NULL, 5),
    ('벨룸', 'CHAOS', 'WEEKLY', 0, NULL, 6),
    ('파풀라투스', 'CHAOS', 'WEEKLY', 0, NULL, 7)
ON CONFLICT (boss_name, difficulty) DO NOTHING;

-- Legacy placeholder remains for historical acquisitions but no longer appears in the catalog.
UPDATE boss_drop_items SET is_active = FALSE WHERE item_name = '솔 에르다 조각';

INSERT INTO boss_drop_items (
    boss_id, item_name, item_image, item_description, drop_rate_tier,
    item_kind, default_quantity, is_active
)
SELECT id, '강렬한 힘의 결정', NULL, '보스 처치 후 판매 가능한 결정석', 'HIGH',
       'CRYSTAL', 1, TRUE
FROM boss_master
ON CONFLICT (boss_id, item_name) DO UPDATE
SET item_kind = EXCLUDED.item_kind,
    default_quantity = EXCLUDED.default_quantity,
    is_active = TRUE;

INSERT INTO boss_drop_items (
    boss_id, item_name, item_image, item_description, drop_rate_tier,
    item_kind, default_quantity, is_active
)
SELECT boss.id, seed.item_name, NULL, NULL, NULL, seed.item_kind, seed.default_quantity, TRUE
FROM (VALUES
    ('자쿰', 'CHAOS', '아쿠아틱 레터 눈장식', 'RANDOM', 1),
    ('자쿰', 'CHAOS', '응축된 힘의 결정석', 'RANDOM', 1),
    ('매그너스', 'HARD', '로얄 블랙메탈 숄더', 'RANDOM', 1),
    ('매그너스', 'HARD', '크리스탈 웬투스 뱃지', 'RANDOM', 1),
    ('매그너스', 'HARD', '저주받은 카이세리움', 'RANDOM', 1),
    ('반반', 'CHAOS', '시간의 조각', 'RANDOM', 1),
    ('피에르', 'CHAOS', '조롱의 조각', 'RANDOM', 1),
    ('블러디 퀸', 'CHAOS', '절규의 조각', 'RANDOM', 1),
    ('벨룸', 'CHAOS', '파멸의 조각', 'RANDOM', 1),
    ('파풀라투스', 'CHAOS', '파풀라투스 마크', 'RANDOM', 1),
    ('스우', 'NORMAL', '녹옥의 보스 반지 상자', 'RANDOM', 1),
    ('스우', 'HARD', '앱솔랩스 방어구 상자', 'RANDOM', 1),
    ('스우', 'HARD', '앱솔랩스 무기 상자', 'RANDOM', 1),
    ('스우', 'HARD', '스우로이드', 'RANDOM', 1),
    ('스우', 'HARD', '루즈 컨트롤 머신 마크', 'RANDOM', 1),
    ('스우', 'HARD', '홍옥의 보스 반지 상자', 'RANDOM', 1),
    ('스우', 'EXTREME', '섬멸병기 스우로이드', 'RANDOM', 1),
    ('스우', 'EXTREME', '루즈 컨트롤 머신 마크', 'RANDOM', 1),
    ('스우', 'EXTREME', '컴플리트 언더컨트롤', 'RANDOM', 1),
    ('스우', 'EXTREME', '백옥의 보스 반지 상자', 'RANDOM', 1),
    ('데미안', 'NORMAL', '루인 포스실드', 'RANDOM', 1),
    ('데미안', 'NORMAL', '녹옥의 보스 반지 상자', 'RANDOM', 1),
    ('데미안', 'HARD', '루인 포스실드', 'RANDOM', 1),
    ('데미안', 'HARD', '앱솔랩스 방어구 상자', 'RANDOM', 1),
    ('데미안', 'HARD', '앱솔랩스 무기 상자', 'RANDOM', 1),
    ('데미안', 'HARD', '데미안로이드', 'RANDOM', 1),
    ('데미안', 'HARD', '마력이 깃든 안대', 'RANDOM', 1),
    ('데미안', 'HARD', '홍옥의 보스 반지 상자', 'RANDOM', 1),
    ('가엔슬', 'NORMAL', '가디언 엔젤 링', 'RANDOM', 1),
    ('가엔슬', 'NORMAL', '녹옥의 보스 반지 상자', 'RANDOM', 1),
    ('가엔슬', 'CHAOS', '가디언 엔젤 링', 'RANDOM', 1),
    ('가엔슬', 'CHAOS', '흑옥의 보스 반지 상자', 'RANDOM', 1),
    ('루시드', 'EASY', '녹옥의 보스 반지 상자', 'RANDOM', 1),
    ('루시드', 'NORMAL', '트와일라이트 마크', 'RANDOM', 1),
    ('루시드', 'NORMAL', '녹옥의 보스 반지 상자', 'RANDOM', 1),
    ('루시드', 'HARD', '아케인셰이드 방어구 상자', 'RANDOM', 1),
    ('루시드', 'HARD', '아케인셰이드 무기 상자', 'RANDOM', 1),
    ('루시드', 'HARD', '루시드로이드', 'RANDOM', 1),
    ('루시드', 'HARD', '트와일라이트 마크', 'RANDOM', 1),
    ('루시드', 'HARD', '몽환의 벨트', 'RANDOM', 1),
    ('루시드', 'HARD', '홍옥의 보스 반지 상자', 'RANDOM', 1),
    ('윌', 'EASY', '녹옥의 보스 반지 상자', 'RANDOM', 1),
    ('윌', 'NORMAL', '트와일라이트 마크', 'RANDOM', 1),
    ('윌', 'NORMAL', '녹옥의 보스 반지 상자', 'RANDOM', 1),
    ('윌', 'HARD', '거울세계의 코어 젬스톤', 'FIXED', 1),
    ('윌', 'HARD', '아케인셰이드 방어구 상자', 'RANDOM', 1),
    ('윌', 'HARD', '아케인셰이드 무기 상자', 'RANDOM', 1),
    ('윌', 'HARD', '트와일라이트 마크', 'RANDOM', 1),
    ('윌', 'HARD', '저주받은 마도서 선택 상자', 'RANDOM', 1),
    ('윌', 'HARD', '홍옥의 보스 반지 상자', 'RANDOM', 1),
    ('더스크', 'NORMAL', '에스텔라 이어링', 'RANDOM', 1),
    ('더스크', 'NORMAL', '녹옥의 보스 반지 상자', 'RANDOM', 1),
    ('더스크', 'CHAOS', '아케인셰이드 방어구 상자', 'RANDOM', 1),
    ('더스크', 'CHAOS', '아케인셰이드 무기 상자', 'RANDOM', 1),
    ('더스크', 'CHAOS', '에스텔라 이어링', 'RANDOM', 1),
    ('더스크', 'CHAOS', '거대한 공포', 'RANDOM', 1),
    ('더스크', 'CHAOS', '흑옥의 보스 반지 상자', 'RANDOM', 1),
    ('듄켈', 'NORMAL', '에스텔라 이어링', 'RANDOM', 1),
    ('듄켈', 'NORMAL', '녹옥의 보스 반지 상자', 'RANDOM', 1),
    ('듄켈', 'HARD', '아케인셰이드 방어구 상자', 'RANDOM', 1),
    ('듄켈', 'HARD', '아케인셰이드 무기 상자', 'RANDOM', 1),
    ('듄켈', 'HARD', '에스텔라 이어링', 'RANDOM', 1),
    ('듄켈', 'HARD', '커맨더 포스 이어링', 'RANDOM', 1),
    ('듄켈', 'HARD', '흑옥의 보스 반지 상자', 'RANDOM', 1),
    ('진 힐라', 'NORMAL', '아케인셰이드 방어구 상자', 'RANDOM', 1),
    ('진 힐라', 'NORMAL', '아케인셰이드 무기 상자', 'RANDOM', 1),
    ('진 힐라', 'NORMAL', '데이브레이크 펜던트', 'RANDOM', 1),
    ('진 힐라', 'NORMAL', '홍옥의 보스 반지 상자', 'RANDOM', 1),
    ('진 힐라', 'HARD', '아케인셰이드 방어구 상자', 'RANDOM', 1),
    ('진 힐라', 'HARD', '아케인셰이드 무기 상자', 'RANDOM', 1),
    ('진 힐라', 'HARD', '데이브레이크 펜던트', 'RANDOM', 1),
    ('진 힐라', 'HARD', '고통의 근원', 'RANDOM', 1),
    ('진 힐라', 'HARD', '흑옥의 보스 반지 상자', 'RANDOM', 1),
    ('선택받은 세렌', 'NORMAL', '데이브레이크 펜던트', 'RANDOM', 1),
    ('선택받은 세렌', 'NORMAL', '흑옥의 보스 반지 상자', 'RANDOM', 1),
    ('선택받은 세렌', 'HARD', '미트라의 코어 젬스톤', 'FIXED', 1),
    ('선택받은 세렌', 'HARD', '데이브레이크 펜던트', 'RANDOM', 1),
    ('선택받은 세렌', 'HARD', '미트라의 분노 선택 상자', 'RANDOM', 1),
    ('선택받은 세렌', 'HARD', '백옥의 보스 반지 상자', 'RANDOM', 1),
    ('선택받은 세렌', 'EXTREME', '미트라의 코어 젬스톤', 'FIXED', 1),
    ('선택받은 세렌', 'EXTREME', '데이브레이크 펜던트', 'RANDOM', 1),
    ('선택받은 세렌', 'EXTREME', '미트라의 분노 선택 상자', 'RANDOM', 1),
    ('선택받은 세렌', 'EXTREME', '백옥의 보스 반지 상자', 'RANDOM', 1),
    ('선택받은 세렌', 'EXTREME', '익셉셔널 해머(얼굴장식)', 'RANDOM', 1),
    ('선택받은 세렌', 'EXTREME', '영롱한 달빛 포션', 'RANDOM', 1),
    ('감시자 칼로스', 'EASY', '백옥의 보스 반지 상자', 'RANDOM', 1),
    ('감시자 칼로스', 'NORMAL', '남겨진 칼로스의 의지 조각', 'FIXED', 3),
    ('감시자 칼로스', 'NORMAL', '니키로이드', 'RANDOM', 1),
    ('감시자 칼로스', 'NORMAL', '백옥의 보스 반지 상자', 'RANDOM', 1),
    ('감시자 칼로스', 'NORMAL', '생명의 연마석', 'RANDOM', 1),
    ('감시자 칼로스', 'CHAOS', '남겨진 칼로스의 의지', 'FIXED', 5),
    ('감시자 칼로스', 'CHAOS', '니키로이드', 'RANDOM', 1),
    ('감시자 칼로스', 'CHAOS', '의지의 에테르넬 방어구 상자', 'RANDOM', 1),
    ('감시자 칼로스', 'CHAOS', '생명의 보스 반지 상자', 'RANDOM', 1),
    ('감시자 칼로스', 'CHAOS', '생명의 연마석', 'RANDOM', 1),
    ('감시자 칼로스', 'EXTREME', '남겨진 칼로스의 의지', 'FIXED', 14),
    ('감시자 칼로스', 'EXTREME', '니키로이드', 'RANDOM', 1),
    ('감시자 칼로스', 'EXTREME', '의지의 에테르넬 방어구 상자', 'RANDOM', 1),
    ('감시자 칼로스', 'EXTREME', '생명의 보스 반지 상자', 'RANDOM', 1),
    ('감시자 칼로스', 'EXTREME', '생명의 연마석', 'RANDOM', 1),
    ('감시자 칼로스', 'EXTREME', '익셉셔널 해머(눈장식)', 'RANDOM', 1),
    ('감시자 칼로스', 'EXTREME', '영롱한 달빛 포션', 'RANDOM', 1),
    ('최초의 대적자', 'EASY', '백옥의 보스 반지 상자', 'RANDOM', 1),
    ('최초의 대적자', 'NORMAL', '이어진 고대의 결의 조각', 'FIXED', 4),
    ('최초의 대적자', 'NORMAL', '대적자로이드', 'RANDOM', 1),
    ('최초의 대적자', 'NORMAL', '백옥의 보스 반지 상자', 'RANDOM', 1),
    ('최초의 대적자', 'NORMAL', '생명의 연마석', 'RANDOM', 1),
    ('최초의 대적자', 'NORMAL', '1단계 소울 에테르', 'RANDOM', 1),
    ('최초의 대적자', 'HARD', '이어진 고대의 결의', 'FIXED', 6),
    ('최초의 대적자', 'HARD', '대적자로이드', 'RANDOM', 1),
    ('최초의 대적자', 'HARD', '고대의 에테르넬 방어구 상자', 'RANDOM', 1),
    ('최초의 대적자', 'HARD', '불멸의 유산', 'RANDOM', 1),
    ('최초의 대적자', 'HARD', '생명의 보스 반지 상자', 'RANDOM', 1),
    ('최초의 대적자', 'HARD', '생명의 연마석', 'RANDOM', 1),
    ('최초의 대적자', 'HARD', '1단계 소울 에테르', 'RANDOM', 1),
    ('최초의 대적자', 'EXTREME', '이어진 고대의 결의', 'FIXED', 16),
    ('최초의 대적자', 'EXTREME', '대적자로이드', 'RANDOM', 1),
    ('최초의 대적자', 'EXTREME', '고대의 에테르넬 방어구 상자', 'RANDOM', 1),
    ('최초의 대적자', 'EXTREME', '불멸의 유산', 'RANDOM', 1),
    ('최초의 대적자', 'EXTREME', '생명의 보스 반지 상자', 'RANDOM', 1),
    ('최초의 대적자', 'EXTREME', '생명의 연마석', 'RANDOM', 1),
    ('최초의 대적자', 'EXTREME', '익셉셔널 해머(훈장)', 'RANDOM', 1),
    ('최초의 대적자', 'EXTREME', '영롱한 달빛 포션', 'RANDOM', 1),
    ('최초의 대적자', 'EXTREME', '1단계 소울 에테르', 'RANDOM', 1),
    ('카링', 'EASY', '뒤엉킨 흉수의 고리 조각', 'FIXED', 1),
    ('카링', 'EASY', '백옥의 보스 반지 상자', 'RANDOM', 1),
    ('카링', 'NORMAL', '뒤엉킨 흉수의 고리 조각', 'FIXED', 5),
    ('카링', 'NORMAL', '카링로이드', 'RANDOM', 1),
    ('카링', 'NORMAL', '혼돈의 칠흑 장신구 상자', 'RANDOM', 1),
    ('카링', 'NORMAL', '백옥의 보스 반지 상자', 'RANDOM', 1),
    ('카링', 'NORMAL', '생명의 연마석', 'RANDOM', 1),
    ('카링', 'NORMAL', '1단계 소울 에테르', 'RANDOM', 1),
    ('카링', 'HARD', '뒤엉킨 흉수의 고리', 'FIXED', 7),
    ('카링', 'HARD', '카링로이드', 'RANDOM', 1),
    ('카링', 'HARD', '흉수의 에테르넬 방어구 상자', 'RANDOM', 1),
    ('카링', 'HARD', '혼돈의 칠흑 장신구 상자', 'RANDOM', 1),
    ('카링', 'HARD', '신념의 연마석', 'RANDOM', 1),
    ('카링', 'HARD', '생명의 보스 반지 상자', 'RANDOM', 1),
    ('카링', 'HARD', '1단계 소울 에테르', 'RANDOM', 1),
    ('카링', 'EXTREME', '뒤엉킨 흉수의 고리', 'FIXED', 18),
    ('카링', 'EXTREME', '카링로이드', 'RANDOM', 1),
    ('카링', 'EXTREME', '흉수의 에테르넬 방어구 상자', 'RANDOM', 1),
    ('카링', 'EXTREME', '혼돈의 칠흑 장신구 상자', 'RANDOM', 1),
    ('카링', 'EXTREME', '신념의 연마석', 'RANDOM', 1),
    ('카링', 'EXTREME', '생명의 보스 반지 상자', 'RANDOM', 1),
    ('카링', 'EXTREME', '익셉셔널 해머(귀고리)', 'RANDOM', 1),
    ('카링', 'EXTREME', '영롱한 달빛 포션', 'RANDOM', 1),
    ('카링', 'EXTREME', '1단계 소울 에테르', 'RANDOM', 1),
    ('벨로나', 'EASY', '백옥의 보스 반지 상자', 'RANDOM', 1),
    ('벨로나', 'NORMAL', '저주받은 원혼의 잔재', 'FIXED', 1),
    ('벨로나', 'NORMAL', '백옥의 보스 반지 상자', 'RANDOM', 1),
    ('벨로나', 'NORMAL', '벨로나로이드', 'RANDOM', 1),
    ('벨로나', 'NORMAL', '생명의 연마석', 'RANDOM', 1),
    ('벨로나', 'NORMAL', '혼돈의 칠흑 장신구 상자', 'RANDOM', 1),
    ('벨로나', 'NORMAL', '2단계 소울 에테르', 'RANDOM', 1),
    ('벨로나', 'HARD', '저주받은 원혼의 잔재', 'FIXED', 2),
    ('벨로나', 'HARD', '생명의 보스 반지 상자', 'RANDOM', 1),
    ('벨로나', 'HARD', '벨로나로이드', 'RANDOM', 1),
    ('벨로나', 'HARD', '신념의 연마석', 'RANDOM', 1),
    ('벨로나', 'HARD', '혼돈의 칠흑 장신구 상자', 'RANDOM', 1),
    ('벨로나', 'HARD', '광기의 에테르넬 방어구 상자', 'RANDOM', 1),
    ('벨로나', 'HARD', '굶주리는 핏빛 원혼', 'RANDOM', 1),
    ('벨로나', 'HARD', '2단계 소울 에테르', 'RANDOM', 1),
    ('찬란한 흉성', 'NORMAL', '황홀한 환상의 단편 조각', 'FIXED', 6),
    ('찬란한 흉성', 'NORMAL', '흉성로이드', 'RANDOM', 1),
    ('찬란한 흉성', 'NORMAL', '백옥의 보스 반지 상자', 'RANDOM', 1),
    ('찬란한 흉성', 'NORMAL', '생명의 연마석', 'RANDOM', 1),
    ('찬란한 흉성', 'NORMAL', '혼돈의 칠흑 장신구 상자', 'RANDOM', 1),
    ('찬란한 흉성', 'NORMAL', '2단계 소울 에테르', 'RANDOM', 1),
    ('찬란한 흉성', 'HARD', '황홀한 환상의 단편', 'FIXED', 18),
    ('찬란한 흉성', 'HARD', '흉성로이드', 'RANDOM', 1),
    ('찬란한 흉성', 'HARD', '환상의 에테르넬 방어구 상자', 'RANDOM', 1),
    ('찬란한 흉성', 'HARD', '황홀한 악몽', 'RANDOM', 1),
    ('찬란한 흉성', 'HARD', '혼돈의 칠흑 장신구 상자', 'RANDOM', 1),
    ('찬란한 흉성', 'HARD', '신념의 연마석', 'RANDOM', 1),
    ('찬란한 흉성', 'HARD', '생명의 보스 반지 상자', 'RANDOM', 1),
    ('찬란한 흉성', 'HARD', '2단계 소울 에테르', 'RANDOM', 1),
    ('림보', 'NORMAL', '왜곡된 욕망의 결정', 'FIXED', 1),
    ('림보', 'NORMAL', '림보로이드', 'RANDOM', 1),
    ('림보', 'NORMAL', '혼돈의 칠흑 장신구 상자', 'RANDOM', 1),
    ('림보', 'NORMAL', '신념의 연마석', 'RANDOM', 1),
    ('림보', 'NORMAL', '생명의 보스 반지 상자', 'RANDOM', 1),
    ('림보', 'NORMAL', '3단계 소울 에테르', 'RANDOM', 1),
    ('림보', 'HARD', '왜곡된 욕망의 결정', 'FIXED', 2),
    ('림보', 'HARD', '림보로이드', 'RANDOM', 1),
    ('림보', 'HARD', '욕망의 에테르넬 방어구 상자', 'RANDOM', 1),
    ('림보', 'HARD', '근원의 속삭임', 'RANDOM', 1),
    ('림보', 'HARD', '혼돈의 칠흑 장신구 상자', 'RANDOM', 1),
    ('림보', 'HARD', '신념의 연마석', 'RANDOM', 1),
    ('림보', 'HARD', '생명의 보스 반지 상자', 'RANDOM', 1),
    ('림보', 'HARD', '3단계 소울 에테르', 'RANDOM', 1),
    ('발드릭스', 'NORMAL', '영원한 충성의 흔적', 'FIXED', 1),
    ('발드릭스', 'NORMAL', '발드릭스로이드', 'RANDOM', 1),
    ('발드릭스', 'NORMAL', '혼돈의 칠흑 장신구 상자', 'RANDOM', 1),
    ('발드릭스', 'NORMAL', '신념의 연마석', 'RANDOM', 1),
    ('발드릭스', 'NORMAL', '생명의 보스 반지 상자', 'RANDOM', 1),
    ('발드릭스', 'NORMAL', '3단계 소울 에테르', 'RANDOM', 1),
    ('발드릭스', 'HARD', '영원한 충성의 흔적', 'FIXED', 2),
    ('발드릭스', 'HARD', '발드릭스로이드', 'RANDOM', 1),
    ('발드릭스', 'HARD', '맹세의 에테르넬 방어구 상자', 'RANDOM', 1),
    ('발드릭스', 'HARD', '죽음의 맹세', 'RANDOM', 1),
    ('발드릭스', 'HARD', '혼돈의 칠흑 장신구 상자', 'RANDOM', 1),
    ('발드릭스', 'HARD', '신념의 연마석', 'RANDOM', 1),
    ('발드릭스', 'HARD', '생명의 보스 반지 상자', 'RANDOM', 1),
    ('발드릭스', 'HARD', '3단계 소울 에테르', 'RANDOM', 1),
    ('유피테르', 'NORMAL', '뒤틀린 갈망의 편린', 'FIXED', 1),
    ('유피테르', 'NORMAL', '유피테르로이드', 'RANDOM', 1),
    ('유피테르', 'NORMAL', '혼돈의 칠흑 장신구 상자', 'RANDOM', 1),
    ('유피테르', 'NORMAL', '신념의 연마석', 'RANDOM', 1),
    ('유피테르', 'NORMAL', '생명의 보스 반지 상자', 'RANDOM', 1),
    ('유피테르', 'NORMAL', '4단계 소울 에테르', 'RANDOM', 1),
    ('유피테르', 'HARD', '뒤틀린 갈망의 편린', 'FIXED', 2),
    ('유피테르', 'HARD', '유피테르로이드', 'RANDOM', 1),
    ('유피테르', 'HARD', '갈망의 에테르넬 방어구 상자', 'RANDOM', 1),
    ('유피테르', 'HARD', '오만의 원죄', 'RANDOM', 1),
    ('유피테르', 'HARD', '혼돈의 칠흑 장신구 상자', 'RANDOM', 1),
    ('유피테르', 'HARD', '신념의 연마석', 'RANDOM', 1),
    ('유피테르', 'HARD', '생명의 보스 반지 상자', 'RANDOM', 1),
    ('유피테르', 'HARD', '4단계 소울 에테르', 'RANDOM', 1),
    ('검은 마법사', 'HARD', '아케인셰이드 방어구 상자', 'RANDOM', 1),
    ('검은 마법사', 'HARD', '아케인셰이드 무기 상자', 'RANDOM', 1),
    ('검은 마법사', 'HARD', '창세의 뱃지', 'RANDOM', 1),
    ('검은 마법사', 'HARD', '백옥의 보스 반지 상자', 'RANDOM', 1),
    ('검은 마법사', 'EXTREME', '아케인셰이드 방어구 상자', 'RANDOM', 1),
    ('검은 마법사', 'EXTREME', '아케인셰이드 무기 상자', 'RANDOM', 1),
    ('검은 마법사', 'EXTREME', '창세의 뱃지', 'RANDOM', 1),
    ('검은 마법사', 'EXTREME', '백옥의 보스 반지 상자', 'RANDOM', 1),
    ('검은 마법사', 'EXTREME', '익셉셔널 해머(벨트)', 'RANDOM', 1)
) AS seed(boss_name, difficulty, item_name, item_kind, default_quantity)
JOIN boss_master AS boss
  ON boss.boss_name = seed.boss_name AND boss.difficulty = seed.difficulty
ON CONFLICT (boss_id, item_name) DO UPDATE
SET item_kind = EXCLUDED.item_kind,
    default_quantity = EXCLUDED.default_quantity,
    is_active = TRUE;
